- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri: 
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: this
    failed_when: "'Ansible has done its job' not in this.content"

# - name: Fail if 'Ansible has done its job' is not in the page content
