---
# vars file for osp.servers
osp_instances:
- name: frontend
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  network: int_network
  floating_ip_network: ext_network
  flavor: m2.small
  security_group: frontend
  meta: "group=frontends,deployment_name=QA"

- name: app1
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  network: int_network
  floating_ip_network: ext_network
  flavor: m2.small
  security_group: apps
  meta: "group=apps,deployment_name=QA"

- name: app2
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  network: int_network 
  floating_ip_network: ext_network
  flavor: m2.small
  security_group: apps
  meta: "group=apps,deployment_name=QA"

- name: db
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  network: int_network 
  floating_ip_network: ext_network
  flavor: m2.small
  security_group: db
  meta: "group=appdbs,deployment_name=QA"

ansible_user: cloud-user
osp_cloud: ospcloud
